### ISSUE TITLE
Periodically sync label siblings

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-label-sync#11]

**Comment by maticzav** [comment]
Github Actions might turn out problematic because they narrow down access token to the particular repository (i.e. in our case, the `prisma-label-sync` repository). Perhaps, we could instead use CircleCI's cron job scheduling.

https://circleci.com/docs/2.0/configuration-reference/#schedule

**Comment by schickling** [comment]
Got it. Let's try that then!

**Comment by maticzav** [comment]
Though we can still use Github Actions and manually add the environment variable, but I need to read Github Actions documentation. Let me know which of the two you prefer.

**Comment by schickling** [comment]
Let's give GH Actions a try to get a better feel for it!

**Comment by janpio** [comment]
Side note: For Prisma 2 siblings are not used any more currently as you can just define 1 sibling per label, which broke for `bug` vs `regression` for us.
