### ISSUE TITLE
Migrate label doc to here?

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma-label-sync#3]
Would it make sense to migrate the labels doc from the [prisma repo](https://github.com/prisma/prisma/blob/master/.github/LABELS.md) to the README of this repo since dozens of other repos use them, not just `prisma`?

**Comment by janpio** [comment]
So we can definitely move that here, it still matches the Prisma common setup of labels, plus the `area/*` labels (which are mentioned in the document as well).

The question is if there is a lot of value of having a free form text description of the labels here at all. Would this live in a `docs` subfolder for example then?

(Prisma 2 label documentation will probably live in the `prisma/specs` repo in a `process` subfolder as we try to define everything about that in that place.)

**Comment by jasonkuhrt** [comment]
Wow pretty old issue 😅 I was a wide-eyed enthusiast 😄.

Need to refresh myself on this issue/repo. While I see a core of labels that can be shared, I also see certain repos/groups of repos needing their own label sets (e.g. `area/*` groups tailored to their domain).

Will come back to this...

**Comment by janpio** [comment]
https://github.com/prisma/prisma/blob/master/.github/LABELS.md will go away with Prisma 1 one day, until then it stays as it is right now.
