### ISSUE TITLE
Unexpected output when merging and approving #29

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-label-sync#31]
When merging and approving #29 I got some unexpected output in Circle:

```
Created siblings:
- Second default(now()) doesn't work (183)
Added kind/bug.
```

![image](https://user-images.githubusercontent.com/183673/62868911-fb074a80-bd16-11e9-8910-78165daa511e.png)

What does this mean exactly?
How can the changes of #29 cause this?
Did something go wrong here or is everything fine?

**Comment by maticzav** [comment]
It means that a new label (`kind/bug`) has been added to #183 (named “Second default...”) because it was listed as a sibling to another, already existing label in that issue.

**Comment by janpio** [comment]
https://github.com/prisma/photonjs/issues/183

So as it had `bug/...` the tool fixed the current labels to include `kind/bug`?

Because https://github.com/prisma/prisma-label-sync/blob/0e62e427eaca5d9a9e5941ca38190a04dfdd4540/src/labels/common/prisma2.ts#L13-L27?
