### ISSUE TITLE
Replace user that executes the changes

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-label-sync#33]
I noticed that currently @timsuchanek appears as the uses that e.g. "removes a label" from an issue when it is deleted. As this is not really true, we should probably create @prismabot or @prismalabelsync (or similar) to do this.

Where is this currently configured?

**Comment by maticzav** [comment]
it depends on the `github token`

**Comment by janpio** [comment]
Ok, got it. 

Configured via Circle CI: https://circleci.com/gh/prisma/prisma-label-sync/edit#env-vars

To get this less confusing, this would have to use a token of a bot user then.

**Comment by janpio** [comment]
We want to change that to some bot account (either @prisma-bot or a new, tool specific one).

**Comment by janpio** [comment]
@prisma-label-sync-bot is now the token saved at Circle CI and doing the changes.
