### ISSUE TITLE
feat: New kind-type labels based on conventional-commit

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma/prisma-label-sync#4]
* proposed new kinds are a subset of the base set of commit types in [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2)
* helps support the following workflow because the `kind` is woven into commit messages, branch names, etc. keeping work focused and increasing signal for peers:

  1. `gi create -l 'kind/perf' -m 'blah blah blah'`
  2. `gco -b feat/<get_id_from_above_result>/blah-blah-blah`
  3. `gpr -l 'kind/perf'`

      ```
      perf: blah blah blah
      Will close #<get id from branch name>
      
      stuff stuff stuff
      ```

--------

#### `kind/perf`

Issue/pr about improving performance of something

#### `kind/test`   

Issue/pr about new tests, or removing/changing/etc. some

Examples:

* [Add tests to compile generated code](https://github.com/prisma/graphqlgen/pull/275)

#### `kind/chore`

Issue/pr about some meta topic for repo health or automation, ci/cd, ...

Examples:

* [chore: better use of prettier for contributors](https://github.com/prisma/graphqlgen/issues/326)
* [Replace CircleCI with Github actions](https://github.com/prisma/prisma-label-sync/issues/1)
* [chore: prettier pass on outstanding files](https://github.com/prisma/graphqlgen/pull/357)

#### `kind/refactor`

Issue/pr is about paying down tech debt, test/source refactoring, architectural implementation change, etc.

Examples:

* [Refactor validation.ts](https://github.com/prisma/graphqlgen/issues/156)

#### `kind/docs`

Issue/pr is about content around and describing code; could be README, guide, reference, JSDoc, ...etc.

Examples:

* [New readme](https://github.com/prisma/graphqlgen/pull/191)

**Comment by jasonkuhrt** [comment]
I also feel I need priority type labels, e.g. `priority/high`. When I'm faced with managing more than a handful of PRs across more than a few days, it can be quite helpful to mark the ones that I want to pay attention to most. Examples where I would use that label right now:

* https://github.com/prisma/graphqlgen/pull/306
* https://github.com/prisma/graphqlgen/pull/149

I also believe marking the priority in a public way helps build a better community.

**Comment by janpio** [comment]
Closing this now as I think you are handling this separately @jasonkuhrt
