### ISSUE TITLE
Created siblings: - Got invalid RPC response without .result property (381)

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-label-sync#40]
Unclear what that actually means:

![image](https://user-images.githubusercontent.com/183673/63516330-16c7d900-c4ed-11e9-9031-7c6f33999d05.png)

https://circleci.com/gh/prisma/prisma-label-sync/167

**Comment by maticzav** [comment]
It means that it added `kind/bug` sibling to an issue "Got invalid...", numbered 381.

**Comment by janpio** [comment]
Ohhhh, that's not an actual error message but just an output of an issue. 

Created https://github.com/maticzav/label-sync/pull/68 to maybe clarify that output.
