### ISSUE TITLE
Support Milestones

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-label-sync#42]
As we are now using milestones for sprint planning, it would be neat if we could have something like label-sync for milestones.

**Comment by maticzav** [comment]
Could you elaborate on the idea?

**Comment by janpio** [comment]
As you know Prisma lives in many repositories. We recently switched from using labels (`release/preview-5`) to using milestones to plan the work we want to achieve in a sprint.

So previously it was enough to add the preview to the label sync configuration, and it would be created across all repositories. Then we could use `label:release/preview-5` in the search to see all the relevant issues.

As GitHub doesn't support cross repository milestones, we have to do the same now for milestones and use `milestone:"Preview 5"` for search. But the creation of these milestones is a similar amount of work as creation of labels: They need a name, a description and a due date.

It would be super neat if we could repurpose (or fork) `label-sync` to work with milestones.

Does that explain what I was thinking about when I wrote this?
Do you think this is a viable approach? And if so, how should we best tackle this?

**Comment by maticzav** [comment]
I think that's a wonderful idea. 🙂

**Comment by janpio** [comment]
Awesome. Should I create this as a feature request over at https://github.com/maticzav/label-sync for it to be added there or should this be a independent fork of that project?

**Comment by maticzav** [comment]
You can add an issue and thoroughly explain the idea there.

**Comment by janpio** [comment]
Now an issue at `label-sync`: https://github.com/maticzav/label-sync/issues/72 (although I found a working workaround for us in the meantime)

**Comment by Jolg42** [comment]
I see this comment about Codetree, is it documented anywhere?
