### ISSUE TITLE
Replace with Terraform Provider

### ISSUE THREAD

**Issue by schickling** [prisma/prisma-label-sync#5]
🤦‍♀️

https://www.terraform.io/docs/providers/github/r/issue_label.html

**Comment by maticzav** [comment]
😂

**Comment by maticzav** [comment]
I haven’t checked the docs thoroughly, but from what I could tell they only cover the `labeling` part and lack `siblings` support. Besides that, considering the time investment and the flexibility we have with `label-sync` I wouldn’t want to switch.
