### ISSUE TITLE
Output current configuration

### ISSUE THREAD

**Issue by janpio** [prisma/prisma-label-sync#59]
It would be neat if there was a way to output the current configuration, that would make it obsolete to look at the code.

Variants:
- Another Circle job that just outputs all repos with the labels that should exist there. You can go to the last commit, open that job and see the overview
- A website is generated and committed to `gh-pages` branch and made available via GitHub pages. You just open the URL to get the currently active configuration.

**Comment by jasonkuhrt** [comment]
I think motivation for this would be less if we had #62. But This would still be valuable though, as it would be the only way to quickly check the concrete values of various repos.

**Comment by janpio** [comment]
Now tracked at https://github.com/maticzav/label-sync/issues/93
